name: swatp_pst_wf
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pandas
  - numpy
  - matplotlib 
  - openpyxl
  - xlrd
  - jupyter 
  - pip
  - notebook 
  - scipy 
  - shapely
  - rtree
  - pyproj
  - pyshp
  - psutil
  - git
  - nbconvert
  - pip:
    - -e ./dependencies/flopy
    - -e ./dependencies/pyemu
    - -e ./dependencies/swatp_pst
    # - flopy
    # - git+https://github.com/modflowpy/flopy.git
    # - pyemu
    # - git+https://github.com/pypest/pyemu.git@develop
    - termcolor
    - tqdm
