name: swatp_pst_wf
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas>=2.0
  - numpy>=1.25
  - matplotlib 
  - openpyxl
  - xlrd
  - jupyter 
  - pip
  - notebook 
  - scipy 
  - shapely
  - rtree
  - pyproj>=2.0
  - pyshp
  - psutil
  - git
  - geopandas
  - netCDF4
  - nbconvert
  - pip:
    # - -e ./dependencies/flopy
    - -e ./dependencies/pyemu
    - -e ./dependencies/swatp_pst
    # - flopy
    # - git+https://github.com/modflowpy/flopy.git
    # - pyemu
    # - git+https://github.com/pypest/pyemu.git@develop
    - termcolor
    - tqdm
    - wget
