
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-12T11:13:49+1300",
 "dirty": false,
 "error": null,
 "full-revisionid": "e799d6fdc3ec14ecfc011656df1a372fcf05f9bd",
 "version": "1.3.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
